{% set version = "0.4.2" %}

package:
  name: typer
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/typer/typer-{{ version }}.tar.gz
  sha256: b8261c6c0152dd73478b5ba96ba677e5d6948c715c310f7c91079f311f62ec03

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - flit-core >=2,<3
    - pip
    - python >=3.6
  run:
    - click >=7.1.1,<9
    - colorama >=0.4.3,<0.5.0
    - python >=3.6
    - shellingham >=1.3.0,<2.0.0

test:
  source_files:
    - docs_src
    - tests
  imports:
    - typer
  requires:
    - pip
    - pytest-cov
    - pytest-sugar
  commands:
    - pip check
    - pytest tests -vv --cov typer --cov-report term-missing:skip-covered --no-cov-on-fail -k "not ((multiple_values and main) or completion_source_bash)" --cov-fail-under 75

about:
  home: https://github.com/tiangolo/typer
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A library for building CLI applications

  description: |
    Typer is library for building CLI applications that users will love using and developers will love creating. Based on Python 3.6+ type hints.

    The key features are:

    Intuitive to write: Great editor support. Completion everywhere. Less time debugging. Designed to be easy to use and learn. Less time reading docs.
    Easy to use: It's easy to use for the final users. Automatic help, and automatic completion for all shells.
    Short: Minimize code duplication. Multiple features from each parameter declaration. Fewer bugs.
    Start simple: The simplest example adds only 2 lines of code to your app: 1 import, 1 function call.
    Grow large: Grow in complexity as much as you want, create arbitrarily complex trees of commands and groups of subcommands, with options and arguments.

  doc_url: https://typer.tiangolo.com
  dev_url: https://github.com/tiangolo/typer

extra:
  recipe-maintainers:
    - dfornika
    - bollwyvl
